### ISSUE TITLE
Добавить ввод параметров к главному классу, подумать над интерфейсом. 

### ISSUE THREAD

**Issue by Lev-Urbnasky** [Lev-Urbnasky/PPLab4SUP#11]
Главный класс - скорее всего GeomFigure, но можно и добавить какой-нибудь другой.

**Comment by gsom95** [comment]
Создам отдельный класс тогда и в нем интерфейс нарисую.

**Comment by Lev-Urbnasky** [comment]
All done - console is a best way.
